# Generated by Django 4.2.6 on 2024-03-20 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription_details',
            old_name='Prescriptio_ID',
            new_name='Prescription_ID',
        ),
        migrations.AddField(
            model_name='user_account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user_account',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_account',
            name='Account',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
