# Generated by Django 4.2.6 on 2024-03-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_rename_prescriptio_id_prescription_details_prescription_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='last_login',
        ),
    ]
