# Generated by Django 4.2.6 on 2024-03-21 00:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_remove_user_account_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('dispensing_q', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='linebot',
            old_name='Birth',
            new_name='birth',
        ),
        migrations.RenameField(
            model_name='linebot',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='linebot',
            old_name='ID_card',
            new_name='id_card',
        ),
        migrations.RenameField(
            model_name='linebot',
            old_name='Line_UID',
            new_name='line_uid',
        ),
        migrations.RenameField(
            model_name='linebot',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='linebot',
            old_name='Phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Efficacy',
            new_name='efficacy',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Medicine_ID',
            new_name='medicine_id',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Medicine_Name',
            new_name='medicine_name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Side_Effects',
            new_name='side_effects',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Stock_Level',
            new_name='stock_level',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='Line_UID',
            new_name='line_uid',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='Prescription_ID',
            new_name='prescription_id',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='Medicine',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='Order_ID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='Purchase_Q',
            new_name='purchase_q',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='Purchase_unitPrice',
            new_name='purchase_unit_price',
        ),
        migrations.RenameField(
            model_name='user_account',
            old_name='Account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='user_account',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user_account',
            old_name='User_ID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='Is_Active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='Medicine',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='Warehouse_ID',
            new_name='warehouse_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='Purchase_date',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='Creation_Date',
        ),
        migrations.AlterField(
            model_name='user_account',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Prescription_Details',
        ),
        migrations.AddField(
            model_name='prescriptiondetails',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.medicine'),
        ),
        migrations.AddField(
            model_name='prescriptiondetails',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='backendApp.prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 3, 21, 0, 28, 19, 474927)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 3, 21, 0, 28, 24, 130519)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 3, 21, 0, 28, 42, 841178)),
            preserve_default=False,
        ),
    ]
