# Generated by Django 4.2.6 on 2024-03-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_alter_warehouse_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='line_uid',
            new_name='line_bot',
        ),
        migrations.AlterField(
            model_name='linebot',
            name='line_uid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
