# Generated by Django 4.2.6 on 2024-03-21 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_rename_line_uid_prescription_line_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='email',
            field=models.EmailField(default=datetime.datetime(2024, 3, 21, 9, 24, 0, 172482), max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
