# Generated by Django 4.2.6 on 2024-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0007_user_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='email',
        ),
        migrations.AddField(
            model_name='user_account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
